sonar.projectKey=lintang.prasetya_sibukpatuh_AZ2FY1HeIGv5U3GvesNl
sonar.projectName=SibukPatuh
sonar.sources=src,api
sonar.exclusions=scripts/**,scratch/**,node_modules/**,dist/**,public/data/**
sonar.cpd.exclusions=scripts/**,scratch/**
